title: Hayward VistaPool
views:
  - title: Pool Overview
    path: pool
    icon: mdi:pool
    cards:
      - type: gauge
        entity: sensor.hayward_vistapool_ph
        name: pH Level
        min: 6.8
        max: 8.2
        severity:
          green: 7.2
          yellow: 7.8
          red: 8.2

      - type: gauge
        entity: sensor.hayward_vistapool_orp
        name: ORP (mV)
        min: 0
        max: 1000
        severity:
          green: 650
          yellow: 750
          red: 900

      - type: gauge
        entity: sensor.hayward_vistapool_chlorine_production
        name: Chlorine Production (%)
        min: 0
        max: 100
        severity:
          green: 70
          yellow: 40
          red: 20

      - type: history-graph
        title: Chemistry & Temperature
        hours_to_show: 24
        entities:
          - sensor.hayward_vistapool_water_temperature
          - sensor.hayward_vistapool_conductivity
          - sensor.hayward_vistapool_chlorine

      - type: entities
        title: Filtration & Heating
        entities:
          - sensor.hayward_vistapool_filtration_mode
          - sensor.hayward_vistapool_heating_setpoint

      - type: glance
        title: System Status
        entities:
          - entity: binary_sensor.hayward_vistapool_filtration
            name: Filtration Running
          - entity: binary_sensor.hayward_vistapool_flow_status
            name: Flow Detected
          - entity: binary_sensor.hayward_vistapool_uv_status
            name: UV System
          - entity: binary_sensor.hayward_vistapool_ph_pump_status
            name: pH Pump
          - entity: binary_sensor.hayward_vistapool_cl_pump_status
            name: Chlorine Pump

      - type: gauge
        entity: sensor.hayward_vistapool_ph_tank_level
        name: pH Tank Level
        min: 0
        max: 100

      - type: gauge
        entity: sensor.hayward_vistapool_cl_tank_level
        name: Chlorine Tank Level
        min: 0
        max: 100

      - type: entities
        title: Connectivity & Misc
        entities:
          - sensor.hayward_vistapool_wifi_signal
          - sensor.hayward_vistapool_rssi
          - sensor.hayward_vistapool_water_level
          - sensor.hayward_vistapool_cell_partial_time
          - sensor.hayward_vistapool_cell_total_time
